In [1]:
import numpy as np

###### create the array

In [2]:
x = np.array([56,12,33,48,71,11,28])

In [3]:
print(x)

[56 12 33 48 71 11 28]


In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x

array([56, 12, 33, 48, 71, 11, 28])

In [8]:
x.dtype

dtype('int32')

In [9]:
a = 3784783874783787847837874837586836873878635863

In [10]:
a

3784783874783787847837874837586836873878635863

In [11]:
a=458**234

In [12]:
a

43905795767991864094969008433853843727765190672755424260323651596770908692463752063349544254446208579317901745636582787109593466824101355870144112225510376448295784994526579552543018884305543044493309296858682300669941538488425682799969171583395923990520786806290244859200327120798115376585778512958867490512130433791363025204928943749007327241909748104181755555514716123701093390972916167581670320194990851096421039547741011361977637389952485047878711869438405433275738041175467479259435617835450594113776974466595004076207385764811051401646402183602801610928800855856199921561691027370889997365249680218466935987350011904

In [15]:
x = np.array([56,12,33,48,71,11,28], dtype=np.int8)

In [16]:
x

array([56, 12, 33, 48, 71, 11, 28], dtype=int8)

In [17]:
x[0] = 200

C:\Users\rajesh\AppData\Local\Temp\ipykernel_16940\3874969223.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x[0] = 200


In [18]:
x[0] = 100

In [19]:
x

array([100,  12,  33,  48,  71,  11,  28], dtype=int8)

In [20]:
x = np.array([56,12,33,48,71,11,28], dtype=np.uint8)

In [21]:
x

array([56, 12, 33, 48, 71, 11, 28], dtype=uint8)

In [22]:
x[0] = -45

C:\Users\rajesh\AppData\Local\Temp\ipykernel_16940\1192193881.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -45 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x[0] = -45


In [23]:
x[0] = 145

In [24]:
x

array([145,  12,  33,  48,  71,  11,  28], dtype=uint8)

In [25]:
x.size

7

In [26]:
x.shape

(7,)

In [27]:
x.min()

11

In [28]:
x.max()

145

In [29]:
x.mean()

49.714285714285715

In [31]:
x.sort()
x

array([ 11,  12,  28,  33,  48,  71, 145], dtype=uint8)

In [32]:
x.std()

43.43702925159686

In [33]:
x.sum()

348

In [34]:
y = np.array([67, 89, 45.34, 69, 11, 35])

In [36]:
type(y)

numpy.ndarray

In [37]:
y.dtype

dtype('float64')

In [38]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [39]:
y[1]

89.0

In [40]:
z = np.array([67, 89, 45.34, 69, 11, True])

In [41]:
z

array([67.  , 89.  , 45.34, 69.  , 11.  ,  1.  ])

In [42]:
z = np.zeros(10)

In [43]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
z = np.zeros(10, dtype=np.int16)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [46]:
o = np.ones(10, dtype=np.int16)
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [49]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [50]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [51]:
np.arange(0, 10, 0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [52]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [53]:
np.linspace(1,11)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

##### array operations

In [55]:
num1 = np.array([56,12,33,14,68,99])
num2 = np.array([28,28,19,39,38,74])

In [56]:
num1 + 10

array([ 66,  22,  43,  24,  78, 109])

In [57]:
num2 / 5

array([ 5.6,  5.6,  3.8,  7.8,  7.6, 14.8])

In [58]:
num1 * 4

array([224,  48, 132,  56, 272, 396])

In [59]:
[56,12,33,14,68,99] * 3

[56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99]

In [60]:
num1 + num2

array([ 84,  40,  52,  53, 106, 173])

In [61]:
num1 - num2

array([ 28, -16,  14, -25,  30,  25])

##### matrix

In [62]:
M = np.array([[4,6,7],[1,2,3],[8,0,2],[9,3,5]])

In [63]:
M

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [65]:
M.shape

(4, 3)

In [66]:
M.dtype

dtype('int32')

In [67]:
M.size

12

In [68]:
M.ndim

2

In [69]:
M[2][1]

0

In [70]:
M[2,1]

0

In [73]:
M[1:3,0:2]

array([[1, 2],
       [8, 0]])

In [74]:
M1 = M.reshape(3,4)
M1

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [76]:
M2 = M.reshape(6,2)
M2

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [78]:
M[1:3,0:2] = np.array([[7,8],[1,1]])
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [79]:
M.reshape(2,-1)

array([[4, 6, 7, 7, 8, 3],
       [1, 1, 2, 9, 3, 5]])

In [82]:
M.reshape(-1,4)

array([[4, 6, 7, 7],
       [8, 3, 1, 1],
       [2, 9, 3, 5]])

In [81]:
M.reshape(4,-1)

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [83]:
M.reshape(-1)

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [84]:
M.flatten()

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [85]:
M.T

array([[4, 7, 1, 9],
       [6, 8, 1, 3],
       [7, 3, 2, 5]])

In [86]:
M.min()

1

In [87]:
help(M.min)

Help on built-in function min:

min(...) method of numpy.ndarray instance
    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function



In [88]:
M.min(axis=1)

array([4, 3, 1, 3])

In [89]:
M.min(axis=0)

array([1, 1, 2])

In [90]:
M.sum(axis=1)

array([17, 18,  4, 17])

In [91]:
M.sum(axis=0)

array([21, 18, 17])

In [92]:
M.sum()

56

In [93]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [94]:
y.reshape(3,2)

array([[67.  , 89.  ],
       [45.34, 69.  ],
       [11.  , 35.  ]])

In [96]:
M.argmax()

9

In [97]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [98]:
y

array([67.  , 89.  , 45.34, 69.  , 11.  , 35.  ])

In [99]:
y.argmax()

1

In [100]:
M.argmin()

6

In [101]:
M.dtype

dtype('int32')

In [102]:
M = M.astype(np.int16)

In [103]:
M

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]], dtype=int16)

In [104]:
M = M.astype(np.float16)
M

array([[4., 6., 7.],
       [7., 8., 3.],
       [1., 1., 2.],
       [9., 3., 5.]], dtype=float16)

In [105]:
x

array([ 11,  12,  28,  33,  48,  71, 145], dtype=uint8)

In [106]:
y = x

In [107]:
y

array([ 11,  12,  28,  33,  48,  71, 145], dtype=uint8)

In [108]:
y[0] = 20

In [109]:
x

array([ 20,  12,  28,  33,  48,  71, 145], dtype=uint8)

In [110]:
id(y)

2489064359376

In [111]:
id(x)

2489064359376

In [112]:
y = x.copy()
y

array([ 20,  12,  28,  33,  48,  71, 145], dtype=uint8)

In [113]:
id(x)

2489064359376

In [114]:
id(y)

2489045780880